### ISSUE TITLE
Wrong License

### ISSUE THREAD

**Issue by CommonCrisis** [kootenpv/textsearch#1]
Hi,

due to using Unidecode this package is not MIT but GPL, right?

**Comment by kootenpv** [comment]
I think both are compatible?

**Comment by CommonCrisis** [comment]
Not if you don't want to publish our code (e.g. for companies).

See:

> Yes, a company can use GPL'd code internally. The main restriction imposed by the GPL is that any source code derived from it or that uses it must also be released under the GPL, but if they aren't modifying or distributing the original GPL code, then they can use the GPLed program.

source: https://stackoverflow.com/questions/3046150/gnu-general-public-license-v2-can-a-company-use-the-licensed-software-for-fre

**Comment by sajal2692** [comment]
Any updates on this? Is it possible to use another library in place of Unidecode? This is preventing me from using this package at work.

**Comment by kootenpv** [comment]
What if you uninstall `Unidecode` afterwards and then just do not use the option flag for it?

**Comment by sajal2692** [comment]
As long as Unidecode stays a mandatory dependency for this package, we can't use this (or other derived packages, see: `contractions` of yours), in our projects if we want the project to have a license other than GPL.

**Comment by sajal2692** [comment]
I found a good discussion about a similar issue here: https://github.com/wagtail/wagtail/issues/3311

In the comments near the end, a suggestion has been made to use this library: https://github.com/anyascii/anyascii

It looks like a close enough drop-in replacement for `unidecode`. 

If you'd like, I can help out and try to raise a PR that replaces `unidecode` with `anyascii`.

**Comment by kootenpv** [comment]
> I found a good discussion about a similar issue here: [wagtail/wagtail#3311](https://github.com/wagtail/wagtail/issues/3311)
> 
> In the comments near the end, a suggestion has been made to use this library: [anyascii/anyascii](https://github.com/anyascii/anyascii)
> 
> It looks like a close enough drop-in replacement for `unidecode`.
> 
> If you'd like, I can help out and try to raise a PR that replaces `unidecode` with `anyascii`.

Thanks a lot, that would be a great and useful contribution!

Speed is important to `textsearch`. So let's also consider how fast it is (then again, just reporting the slowdown will be good enough probably)

**Comment by kootenpv** [comment]
Sweet. It's now available per 

    pip install --no-cache textsearch==0.0.21

**Comment by sajal2692** [comment]
Awesome. I think we can close this issue now.

**Comment by kootenpv** [comment]
Cool, thanks for helping out!
