### ISSUE TITLE
Return unique tokens

### ISSUE THREAD

**Issue by 91Abdullah** [kootenpv/textsearch#5]
Kudos for the wonderful and one of the most helpful library!

Currently, returned list contains all the tokens found in the text but is there any way that it'll only return unique words?

For example,

if returned list is [Buprenorphine, Buprenorphine, Buprenorphine] then it should only return [Buprenorphine].

Thanks in advance.

**Comment by kootenpv** [comment]
Thanks! 

Why not just use a set on the output?
