### ISSUE TITLE
Overlapping results when using findall

### ISSUE THREAD

**Issue by nraybi** [kootenpv/textsearch#6]
Steps to reproduce:

```python
import textsearch
ts_test = textsearch.TextSearch(case='ignore', returns='match')
ts_test.add(['aaa', 'bbb', 'aaa bbb ccc' ])
print(ts_test.findall('aaa bbb ccc'))
```
will result in
`['aaa', 'aaa bbb ccc']`

```python
ts_test = textsearch.TextSearch(case='ignore', returns='match')
ts_test.add(['aaa', 'bbb', 'ccc', 'aaa bbb ccc ddd' ])
print(ts_test.findall('aaa bbb ccc ddd'))
```
will result in
`['aaa', 'bbb', 'aaa bbb ccc ddd']`

etc..

This happens because `findall` replaces only the last keyword in the list if the last keyword's length is smaller than the length of the current keywords.
![image](https://user-images.githubusercontent.com/112481360/187474377-43b68fbd-aabb-43bd-a82b-29047bf836bb.png)
it can be fixed by replacing the line `keywords[-1] = result` with
```python
keep_up_to_ind = next((i for i, k in enumerate(keywords) if k[1] == start), -1)  # find the first index of a keyword with the same starting position
keywords = keywords[:keep_up_to_ind]  # keep keyword up to this index
keywords.append(result)  # append the current keyword that contains all of the removed keywords
```
This will replace all the previous keywords overlapping with the current.

**Comment by kootenpv** [comment]
Thanks a lot for doing the research! I'd be glad to merge it in when you make a PR!

**Comment by kootenpv** [comment]
you can get the new version using

`pip install -U --no-cache textsearch>=0.0.24`
